#!/bin/zsh
# check if all commands are installed

local black='\e[30m'
local red='\e[31m'
local green='\e[32m'
local blue='\e[34m'
local purple='\e[35m'
local cyan='\e[36m'
local gray='\e[37m'
local white='\e[00m'

if [ ! -z "$1" ]; then
  echo 'package managers:'
  echo " - distrib:   ${blue}✓${gray}"
  echo " - asdf:      ${cyan}✓${gray}"
  echo " - cargo:     ${green}✓${gray}"
  echo " - scoop:     ${purple}✓${gray}"
  echo " - not found: ${red}✘${gray}"
fi

local cmds=(
  '7z'
  'bat'
  'cargo'
  'chezmoi'
  'code'
  'delta'
  'difft'
  'direnv'
  'dust'
  'eza'
  'fd'
  'fzf'
  'git'
  'go'
  'helm'
  'helmfile'
  'jaq'
  'kops'
  'kubectl'
  'kubectx'
  'meld'
  'node'
  'paper'
  'python'
  'rg'
  'starship'
  'terraform'
  'tldr'
  'vivid'
  'yazi'
  'zoxide'
)

for cmd in "${cmds[@]}"; do
  local result=$(type -a $cmd | grep -oE 'asdf|scoop|cargo|bin')
  case $result in
    *asdf*) echo "${cyan}✓${gray} $cmd";;
    *cargo*) echo "${green}✓${gray} $cmd";;
    *scoop*) echo "${purple}✓${gray} $cmd";;
    *bin*) echo "${blue}✓${gray} $cmd";;
    *) echo "${red}✘${gray} $cmd";;
  esac
done
