#!/bin/zsh

# https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode-using-a-single-key-binding
# Switch between Ripgrep mode and fzf filtering mode (CTRL-T)
rm -f /tmp/rg-fzf-{r,f}
local rg_prefix="rg --column --line-number --no-heading --color=always --smart-case --glob '!{$GREP_EXCLUDE}' "
local initial_query="${*:-}"
fzf --ansi --disabled --query "$initial_query" \
    --bind "start:reload:$rg_prefix {q}" \
    --bind "change:reload:sleep 0.1; $rg_prefix {q} || true" \
    --bind 'ctrl-t:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] &&
      echo "rebind(change)+change-prompt(1. ripgrep> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r" ||
      echo "unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f"' \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --prompt '1. ripgrep> ' \
    --delimiter : \
    --header 'CTRL-T: Switch between ripgrep/fzf' \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'right,50%,border-left,+{2}+3/2,~3' \
    --bind "enter:become($EDITOR {1} +{2})"
