#!/bin/zsh

if [ -z "$1" ]; then
  echo 'usage: ssh-cp-id user@hostname [path to id_rsa.pub]'
  echo 'if [path to id_rsa.pub] is undefined, ~/.ssh/id_rsa.pub will be used'
  exit 1
fi

cat ${2:-~/.ssh/id_rsa.pub} | ssh $1 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'
