#!/bin/zsh

(( $+commands[yazi] )) || return 1

yazi_tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
yazi "$@" --cwd-file="$yazi_tmp"
if cwd="$(cat -- "$yazi_tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
  builtin cd -- "$cwd"
fi
rm -f -- "$yazi_tmp"
unset yazi_tmp
